# Generated by Django 5.0.1 on 2024-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_services_remove_product_image_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
