# Generated by Django 5.0.1 on 2024-06-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_services_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='order_services',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.services'),
        ),
    ]
